keys:
  - &loliIsland age1kfzd6saww8rsfhe5zs7gky2pyk6yl5jkew9gypyrk00qmadw7p3qdkdlys
  - &loliIslandCanokey age1yubikey1qdt7dcx4973y9gj98yety02xf5dp9q4xpmkrp9tdwcntmc0t0sz8vvuywml

creation_rules:
  - path_regex: ^secrets/.*\.ya?ml$
    key_groups:
      - age:
          - *loliIsland
          - *loliIslandCanokey
